services:
  - type: web
    name: movie-recommendation-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app-test:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16 