services:
  - type: web
    name: movie-recommendation-system
    env: python
    buildCommand: pip install -r requirements-simple.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16 